routes/admin.php
        Route::get('all', 'Admin\UsersController@index')->name('users.all');
    });
    Route::group(['middleware' => ['permission:create user']], function () {
        Route::get('create', 'Admin\UsersController@create')->name('users.create');
        Route::post('create', 'Admin\UsersController@store')->name('users.store');
    });
    Route::group(['middleware' => ['permission:update user']], function () {
        Route::get('edit/{user}', 'Admin\UsersController@edit')->name('users.edit');
        Route::post('edit/{user}', 'Admin\UsersController@update')->name('users.update');
    });
    Route::group(['middleware' => ['permission:delete user']], function () {
        Route::get('delete/{user}', 'Admin\UsersController@destroy')->name('users.destroy');
    });
});
Route::group(['prefix'=>'providers'],function () {

    Route::group(['middleware' => ['permission:read provider']], function () {
        Route::get('all', 'Admin\ProvidersController@index')->name('providers.all');
    });
    Route::group(['middleware' => ['permission:create provider']], function () {
        Route::get('create', 'Admin\ProvidersController@create')->name('providers.create');
        Route::post('create', 'Admin\ProvidersController@store')->name('providers.store');
    });
    Route::group(['middleware' => ['permission:read provider']], function () {
        Route::get('/{provider}', 'Admin\ProvidersController@show')->name('providers.show');
    });
    Route::group(['middleware' => ['permission:update provider']], function () {
        Route::get('edit/{provider}', 'Admin\ProvidersController@edit')->name('providers.edit');
        Route::post('edit/{provider}', 'Admin\ProvidersController@update')->name('providers.update');
    });
    Route::group(['middleware' => ['permission:delete provider']], function () {
        Route::get('delete/{provider}', 'Admin\ProvidersController@destroy')->name('providers.destroy');
    });
});
Route::group(['prefix'=>'tasks'],function () {

//    Route::group(['middleware' => ['permission:read tasks']], function () {
        Route::get('all', 'Admin\TaskController@index')->name('tasks.all');
        Route::get('myTasks', 'Admin\TaskController@myTasks')->name('tasks.marketer');
        Route::get('task/{task}', 'Admin\TaskController@show')->name('tasks.show');
        Route::get('task/{task}/{user}', 'Admin\TaskController@showUser')->name('tasks.user.show');
        Route::get('myTask/{task}', 'Admin\TaskController@myTask')->name('tasks.marketer.show');
        Route::get('myTask/{task}/{status}', 'Admin\TaskController@taskStatus')->name('tasks.marketer.status');
//    });
//    Route::group(['middleware' => ['permission:create tasks']], function () {
        Route::get('create', 'Admin\TaskController@create')->name('tasks.create');
        Route::post('users', 'Admin\TaskController@users')->name('tasks.users');
        Route::post('create', 'Admin\TaskController@store')->name('tasks.store');
//    });
//    Route::group(['middleware' => ['permission:update tasks']], function () {
        Route::get('edit/{task}', 'Admin\TaskController@edit')->name('tasks.edit');
        Route::post('edit/{task}', 'Admin\TaskController@update')->name('tasks.update');
        Route::post('task/comment', 'Admin\TaskController@addComment')->name('tasks.comment');
//    });
//    Route::group(['middleware' => ['permission:delete tasks']], function () {
        Route::get('delete/{task}', 'Admin\TaskController@destroy')->name('tasks.destroy');
//    });
});
Route::group(['middleware' => ['permission:sort sections']], function () {
    Route::get('/sectionSort','Admin\SectionsController@index')->name('sectionSort');
    Route::post('/sectionSort','Admin\SectionsController@store')->name('sectionSort.store');
});
Route::group(['middleware' => ['permission:control themes section']], function () {
    Route::get('themes', 'Admin\ThemesController@index')->name('themes');
    Route::get('activeTheme/{active}', 'Admin\ThemesController@active')->name('activeTheme');
    Route::post('visible', 'Admin\ThemesController@visible')->name('visible');

});
//Route::group(['middleware' => ['permission:edit sections setting|control aboutUs section']], function () {
    Route::put('/section/setting', 'Admin\SectionsController@update')->name('section.setting.update');
//});
//Route::group(['middleware' => ['permission:control partners section']], function () {
    Route::get('brandLogo', 'Admin\PartnersController@partners')->name('partners');
    Route::post('brandLogo', 'Admin\PartnersController@storeLogo')->name('partners.storeLogo');
    Route::post('brandName', 'Admin\PartnersController@store')->name('partners.store');
    Route::get('partnersLogo', 'Admin\PartnersController@logo');
    Route::get('images', 'Admin\PartnersController@showImages');
    Route::get('deleteLogo/{image}', 'Admin\PartnersController@delete')->name('deleteLogo');
    Route::get('deleteBackground/{image}', 'Admin\PartnersController@deleteBackground')->name('deleteBackground');
    Route::put('updateLogo/{image}','Admin\PartnersController@update')->name('updateLogo');
//});


//Route::group(['middleware' => ['permission:control blog section']], function () {
    Route::get('/post/{id}', 'Admin\PostsController@destroy')->name('post.destroy');
    Route::resource('posts', 'Admin\PostsController');
    Route::get('deleteImage/{media}','Admin\PostsController@deleteImage')->name('post.deleteImage');
    Route::resource('BlogCategory', 'Admin\BlogCategoryController');
    Route::get('/catBlog/{id}', 'Admin\BlogCategoryController@destroy')->name('catBlog.destroy');
    Route::get('/blogSetting', 'Admin\PostsController@setting');
    Route::get('blog/deleteImage/{media}','Admin\PostsController@deleteImage')->name('blog.deleteImage');
//    Route::get('product/deleteImage/{media}','Admin\ProductsController@deleteImage')->name('products.deleteImage');


//});

/********** product *********/
//Route::group(['middleware' => ['permission:control products section']], function () {
    Route::resource('products', 'Admin\ProductsController');
    Route::get('/product/{id}', 'Admin\ProductsController@destroy')->name('product.destroy');
    Route::get('product/deleteImage/{media}','Admin\ProductsController@deleteImage')->name('products.deleteImage');

//});
//Route::group(['middleware' => ['permission:control productCategory section']], function () {
    Route::resource('categoryProduct', 'Admin\CategoryProductController');
    Route::get('/catProduct/{id}', 'Admin\CategoryProductController@destroy')->name('catProduct.destroy');
    Route::get('productSetting','Admin\CategoryProductController@setting');
    Route::get('categories/subCategory/{category}','Admin\CategoryProductController@subCategory');
    Route::get('categories/attributes/{category}','Admin\CategoryProductController@attributes');
    Route::get('deleteSize/{id}','Admin\AttributesController@destroy')->name('removeSize');

//});
Route::group(['middleware' => ['permission:approve product']], function () {
    Route::post('product/status/{product}', 'Admin\ProductsController@status')->name('product.status');
});
Route::group(['prefix'=>'attributes'],function () {

//    Route::group(['middleware' => ['permission:control attributes']], function () {
        Route::get('all', 'Admin\AttributesController@index')->name('attributes.all');
        Route::post('create', 'Admin\AttributesController@store')->name('attributes.store');
        Route::put('edit/{attribute}', 'Admin\AttributesController@update')->name('attributes.update');
//        Route::get('delete/{user}', 'Admin\UsersController@destroy')->name('users.destroy');
//    });
});
/*********************end products ************/

//Route::group(['middleware' => ['permission:control slider section']], function () {
    Route::resource('slider', 'Admin\SliderController');
    Route::get('deleteSlider/{slider}', 'Admin\SliderController@destroy')->name('slider.delete');
//});

//Route::group(['middleware' => ['permission:update website settings']], function () {
    Route::get('settings', 'Admin\SettingsController@edit')->name('settings.edit');
    Route::put('/settings', 'Admin\SettingsController@update')->name('settings.update');
//});
/* order and request */
Route::get('orders','Admin\OrderController@index')->name('orders');
Route::get('orders/review/{order}','Admin\OrderController@review')->name('orders.review');
Route::get('orders/{order}/{status}', 'Admin\OrderController@update')->name('orders.update');

Route::get('requests','Admin\RequestsController@service')->name('requests');
Route::get('requestsPage','Admin\RequestsController@page')->name('requestsPage');
/*contact us */
Route::get('message','Admin\MessagesController@index')->name('message');
/* instgram */
Route::group(['middleware' => ['permission:control instagram section']], function () {
    Route::resource('instagrams', 'Admin\InstagramController');
    Route::get('/instagram/{id}', 'Admin\InstagramController@destroy')->name('instagram.destroy');

});
/* twitter */
Route::group(['middleware' => ['permission:control twitter section']], function () {
    Route::resource('twitters', 'Admin\TwitterController');
    Route::get('/twitter/{id}', 'Admin\TwitterController@destroy')->name('twitter.destroy');
    Route::get('deleteImage/{media}','Admin\TwitterController@deleteImage')->name('twitter.deleteImage');


});
/* shiping */
Route::prefix('shipping')->group(function (){
    Route::get('/', 'Admin\ShippingController@edit')->name('shipping.edit');
    Route::post('/{country}', 'Admin\ShippingController@update')->name('shipping.update');
//    Route::post('store', 'Admin\ShippingController@store')->name('shipping.store');
    Route::get('delete/{country}', 'Admin\ShippingController@destroy')->name('settings.delete.shipping');

});
//profile
Route::get('profile','Admin\SettingsController@editProfile')->name('profile.edit');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


Route::group(['prefix' => 'admin'], function () {
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});




/*route front end */
Route::get('/','Frontend\HomeController@index');
Route::get('pages/{slug}','Frontend\HomeController@page')->name('pages');
Route::get('blog','Frontend\HomeController@blogg')->name('blog');
Route::get('blog/{post}','Frontend\HomeController@blog')->name('blog');

/******** cat product **********/
Route::get('categories','Frontend\HomeController@categoriesProduct')->name('categoryProduct');
//Route::post('categories','Frontend\HomeController@categoriesProduct')->name('categoryProduct');
Route::post('categoriesFilter','Frontend\HomeController@categoriesProduct')->name('categories.fil');
Route::get('search/product','Frontend\HomeController@search')->name('products.search');
Route::get('category/{category}','Frontend\HomeController@productsCategory')->name('products');
Route::post('category/{category}','Frontend\HomeController@productsCategory')->name('products.filter');
Route::get('product/{product}','Frontend\HomeController@product')->name('product');
Route::get('checkStock/{product}/{value}','Frontend\OrderController@checkStock')->name('checkStock');
Route::get('size/{size}','Frontend\HomeController@size')->name('size');
Route::post('size/{size}','Frontend\HomeController@size')->name('categories.filter');
Route::get('sortProduct/{request}','Frontend\HomeController@sortProduct')->name('sortProduct');

/**********  end cat product *********/

Route::get('contactUs',function (){
    return view('frontend.contactUs') ;
});
Route::get('/sectionSort','Frontend\HomeController@sortSection')->name('sectionSort');

Route::get('lang/{locale}', 'LocalizationController@index')->name('language.change');
//Route::get('/','Frontend\HomeController@index')->name('home');

/************** brand *********/
Route::get('brands','Frontend\HomeController@brands')->name('brands');
Route::get('collections/{brand}','Frontend\HomeController@brand')->name('collections.brand');
Route::post('collections/{brand}','Frontend\HomeController@brand')->name('collections.filter');
Route::get('sizeBrand/{brand}/{size}','Frontend\HomeController@sizeBrand')->name('sizeBrand');
Route::post('sizeBrand/{brand}','Frontend\HomeController@sizeBrand')->name('sizeBrand.filter');

/*************** sale ***********/
Route::get('sale','Frontend\HomeController@sale')->name('sale');
Route::post('sale','Frontend\HomeController@sale')->name('sale.filter');
/***** newReleases ***/
Route::get('newReleases','Frontend\HomeController@newReleases')->name('newReleases');
Route::post('newReleases','Frontend\HomeController@newReleases')->name('newReleases.filter');

/* product order form */
Route::post('order','Frontend\OrderController@store')->name('order.store');
Route::post('orderNow','Frontend\OrderController@orderNow')->name('order.now');
Route::post('product/addToCart','Frontend\OrderController@addToCart')->name('product.addToCart');
Route::get('product/deleteFromCart/{id}','Frontend\OrderController@deleteFromCart')->name('product.deleteFromCart');
/************** account *********/
Route::get('account','Frontend\HomeController@account')->name('account');
// quickviwe
Route::get('productRev/{product}','Frontend\HomeController@quickview')->name('product.quickview');

//service request
Route::post('request','Frontend\RequestsController@store')->name('request');
//contact us
Route::post('message','Frontend\MessagesController@store')->name('message');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('checkout', 'Frontend\OrderController@checkout')->name('checkout');
    Route::post('payment', 'Frontend\PayPalController@payment')->name('order.payment');
    Route::get('cancel', 'Frontend\PayPalController@cancel')->name('payment.cancel');
    Route::get('payment/success', 'Frontend\PayPalController@success')->name('payment.success');
    Route::post('/updateActiveAddress/{address}','Frontend\OrderController@updateAddress');

});
Route::get('/home', 'Frontend\HomeController@index')->name('home');
/* cart*/
Route::get('/cart', 'Frontend\HomeController@cart')->name('cart');
Route::get('cart/update/{id}', 'Frontend\OrderController@update')->name('cart.update');
/* profile */
Route::get('/profile','Frontend\UserAddressController@profile')->name('profile');
Route::get('/address','Frontend\UserAddressController@index')->name('address');
Route::post('/store','Frontend\UserAddressController@store')->name('address.store');
Route::get('/edit/{id}','Frontend\UserAddressController@edit')->name('address.edit');
Route::post('/update/{id}','Frontend\UserAddressController@update')->name('address.update');
Route::get('/delete/{id}','Frontend\UserAddressController@destroy')->name('address.delete');

app/Instagram.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Instagram extends Model
{
    use Mediable;

}

resources/views/admin/instagram/create.blade.php
@extends('admin.layout.master')
@section('title','Create Instagram Images')
@section('content')
    <div class="page-inner">

        <div class="row">
            <div class="col-md-12">
                <form method="POST" action="{{route('admin.instagrams.store')}}" enctype="multipart/form-data" file="true">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">{{__('instagram Images')}}</div>
                        </div>

                        <div class="card-body">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="link">{{ __('Instagram Link') }}</label>
                                        <input  class="form-control" name="link" id="link" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="img">{{__('Upload Image')}}</label>
                                        <input type="file" name="img" class="form-control-file" id="img" required>
                                    </div>
                                    <div class="form-group" id="imgPreview" >
                                        <img src="" class="img-fluid" alt="" width="300px" height="300px">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-action">
                            <button type="submit" class="btn btn-success float-right">{{__('Add')}}</button>

                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

@stop
@section('script')
    <script>
        $('input[type="file"]').on('change', function (e) {
            let fileName = e.target.files[0].name,
                reader = new FileReader();

            $(e.target).siblings('label').text(fileName);

            reader.onload = function (event) {
                $('#imgPreview img').attr('src', event.target.result);
            };

            reader.readAsDataURL(e.target.files[0]);
            $('#imgPreview').show();
        });

        $(document).ready(function() {
            $('.summernote').summernote({
                tabsize: 2,
                height: 300,
                minHeight: null,
                maxHeight: null,
                focus: true,
                lang: '{{ config("app.locale") }}',
                toolbar: [
                    // [groupName, [list of button]]
                    ['font', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['style', 'ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['style', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
                    ['insert', [ 'table','hr','video','link']],
                    ['custom', ['picture']],
                    ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
                    ['misc', ['fullscreen', 'undo', 'redo', 'help', 'codeview']]
                ],
            });
        });


    </script>
@stop

resources/views/admin/instagram/edit.blade.php
@extends('admin.layout.master')
@section('title','Update Instagram Images')
@section('content')
    <div class="page-inner">

        <div class="row">
            <div class="col-md-12">
                <form method="POST" action="{{route('admin.instagrams.update',$instagram->id)}}" enctype="multipart/form-data" file="true">
                    @csrf
                    @method('PUT')
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">{{__('Updata Instagram Image')}}</div>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">

                                        <label for="link">{{ __('Instagram Link') }}</label>
                                        <input  class="form-control" name="link" id="link" value="{{$instagram->link}}" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="img">{{__('Upload Image')}}</label>
                                        <input type="file" name="img"  id="img" multiple >
                                    </div>
                                    <div class="form-group">

                                        @if($instagram->hasMedia('instagram'))
                                            <div class="form-group" id="imgPreview">
                                                <img src="{{$instagram->lastMedia('instagram')->getUrl()}}" width="100px" height="100px">
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-action">
                            <button type="submit" class="btn btn-success float-right">{{__('Update')}}</button>

                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

@stop
@section('script')
    <script>
        $('input[type="file"]').on('change', function (e) {
            let fileName = e.target.files[0].name,
                reader = new FileReader();

            $(e.target).siblings('label').text(fileName);

            reader.onload = function (event) {
                $('#imgPreview img').attr('src', event.target.result);
            };

            reader.readAsDataURL(e.target.files[0]);
            $('#imgPreview').show();
        });

        $(document).ready(function() {
            $('.summernote').summernote({
                tabsize: 2,
                height: 300,
                minHeight: null,
                maxHeight: null,
                focus: true,
                lang: '{{ config("app.locale") }}',
                toolbar: [
                    // [groupName, [list of button]]
                    ['font', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['style', 'ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['style', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
                    ['insert', [ 'table','hr','video','link']],
                    ['custom', ['picture']],
                    ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
                    ['misc', ['fullscreen', 'undo', 'redo', 'help', 'codeview']]
                ],
            });
        });
    </script>
@stop

resources/views/admin/instagram/index.blade.php
@extends('admin.layout.master')
@section('title','Instagram')
@section('content')
    <div class="row row-card-no-pd">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-head-row card-tools-still-right">
                        <h4 class="card-title">{{__('Instagram')}}</h4>
                    </div>

                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive table-hover table-sales">
                                <table class="table">
                                    <thead>
                                    <th>{{__('Image')}}</th>
                                    <th>{{__('Link')}}</th>
                                    <th>{{__('Action')}}</th>
                                    </thead>
                                    @if($instagrams->count() > 0)
                                        @foreach($instagrams as $instagram)
                                            <tbody>
                                            <tr>
                                                <td>
                                                    @if($instagram->hasMedia('instagram'))
                                                        <div class="flag">
                                                            <img width="80" height="80" src="{{ $instagram->lastMedia('instagram')->getUrl() }}">
                                                        </div>
                                                    @endif
                                                </td>
                                                <td>{{$instagram->link}}</td>

                                                <td>

                                                    <a href="{{route('admin.instagrams.edit',$instagram->id)}}" class="btn btn-info btn-xs">
                                                        <i class='fa fa-edit'></i>{{__('Edit')}}
                                                    </a>

                                                    <button class="btn btn-danger btn-xs" type="submit" onclick="removeInstagram('{{route('admin.instagram.destroy',$instagram->id)}}')">
                                                        <i class="fas fa-trash"></i> {{__('Delete')}}
                                                    </button>
                                                </td>
                                            </tr>

                                            </tbody>
                                        @endforeach
                                    @endif
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

@section('script')
    <script>
        function removeInstagram(url, e) {
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this imaginary file!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = url;
                    }
                });
        };

    </script>
@stop